# Generated by Django 3.2.9 on 2022-01-03 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Website',
        ),
        migrations.DeleteModel(
            name='WebsiteEvents',
        ),
        migrations.DeleteModel(
            name='WebsiteModules',
        ),
        migrations.DeleteModel(
            name='WebsiteTeam',
        ),
    ]
