# Generated by Django 3.2.9 on 2022-01-23 08:37

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wsite', '0002_auto_20220103_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_pre_heading', models.CharField(default='Play, Learn and Grow', max_length=1000)),
                ('hero_heading', models.CharField(default='Lets Learn Together', max_length=1000)),
                ('hero_paragraph_1', models.TextField(default='Human beings are social animals and we have been successful in becoming the most dominant species, by way of our team effort. Great news is we thrive when we work as a team. But then why should learning activity be a isolated and single person effort. At CoCognito, we believe learning need not be a single person effort. Rather it should be a social activity.')),
                ('hero_paragraph_2', models.TextField(default='That way it is more engaging, lasting and should be say, more FUN :-) So we have built quizzes here on variety of subjects that you can practice together with your friend(s). Remember, idea here is not to compete. But to work together to problem solve a situation. You share ideas, discuss them, suggest point of views, take suggestions and finally make a decision. Sounds fun, rite?')),
                ('hero_end_line', models.CharField(default='Come lets CoCognito !', max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Content',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', help_text='size of logo must be 195*65 and format must be png image file', keep_meta=True, null=True, quality=75, size=[195, 65], upload_to='website/images/partner /')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=255)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', help_text='size of logo must be 500*500 and format must be png image file', keep_meta=True, null=True, quality=75, size=[500, 500], upload_to='website/images/team/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='Description not provided yet.')),
                ('testimonial_type', models.CharField(choices=[('p', 'Parent'), ('s', 'Student'), ('m', 'Moderator')], max_length=1)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', help_text='size of logo must be 300*300 and format must be png image file', keep_meta=True, null=True, quality=75, size=[300, 300], upload_to='website/images/testimonial /')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Team',
            },
        ),
    ]
