# Generated by Django 3.2.9 on 2022-01-23 13:17

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0003_content_partner_team_testimonial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', help_text='size of logo must be 195*65 and format must be png image file', keep_meta=True, null=True, quality=75, size=[195, 65], upload_to='website/images/partner/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', help_text='size of logo must be 300*300 and format must be png image file', keep_meta=True, null=True, quality=75, size=[300, 300], upload_to='website/images/team/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', help_text='size of logo must be 300*300 and format must be png image file', keep_meta=True, null=True, quality=75, size=[300, 300], upload_to='website/images/testimonial/'),
        ),
    ]
