# Generated by Django 3.1.6 on 2021-04-26 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0002_auto_20210427_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmentproject',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 1, 36, 52, 673588)),
        ),
        migrations.AlterField(
            model_name='developmentproject',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 1, 36, 52, 673588)),
        ),
    ]
