# Generated by Django 3.1.6 on 2021-04-28 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0003_auto_20210427_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmentproject',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 1, 35, 21, 924502)),
        ),
        migrations.AlterField(
            model_name='developmentproject',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 1, 35, 21, 924502)),
        ),
    ]
