# Generated by Django 3.1.6 on 2021-06-21 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0007_auto_20210520_0848'),
        ('dev', '0008_auto_20210509_2145'),
    ]

    operations = [
    ]
