# Generated by Django 3.2.7 on 2021-09-26 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0014_auto_20210628_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmentproject',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 4, 38, 10, 77899)),
        ),
        migrations.AlterField(
            model_name='developmentproject',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 26, 4, 38, 10, 77899)),
        ),
    ]
