# Generated by Django 3.1.4 on 2020-12-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth format must be [yyyy/mm/dd] or [yyyy-mm-dd]', null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='players',
            field=models.CharField(choices=[('1', 'Single Player'), ('2', 'Two Players'), ('3', 'Three Players')], default='1', max_length=1),
        ),
    ]
