# Generated by Django 2.2.4 on 2020-10-21 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='attempt',
            old_name='updated_on',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='guardian',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='guardian',
            old_name='updated_on',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='updated_on',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='updated_on',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='updated_on',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='updated_on',
            new_name='modified_at',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='team',
            name='created_on',
        ),
        migrations.AddField(
            model_name='quiz',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
