# Generated by Django 3.1.4 on 2021-01-06 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='learning_purpose',
            field=models.BooleanField(default=False, help_text='By checking Learning purpose some changes will be applied to this quiz, it will only visible for learning resource, quiz will be different from main quizes, student can only use this quiz for learning purpose'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='submission_control',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='application.screen'),
            preserve_default=False,
        ),
    ]
