# Generated by Django 3.0.2 on 2020-11-12 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20201112_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(blank=True, default='e', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='submission_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_by', to='application.Screen'),
        ),
    ]
