# Generated by Django 2.2.4 on 2020-10-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20201021_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_hint_file',
            field=models.FileField(blank=True, null=True, upload_to='static/Uploads/'),
        ),
        migrations.AddField(
            model_name='question',
            name='audio_hint_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='image_hint_file',
            field=models.FileField(blank=True, null=True, upload_to='static/Uploads/'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_hint_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
