# Generated by Django 3.1.4 on 2021-01-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20201231_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('1', 'Single Player'), ('2', 'Two Player'), ('3', 'Three Player')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='players',
            field=models.CharField(choices=[('2', 'Two Players'), ('3', 'Three Players')], default='1', max_length=1),
        ),
    ]
