# Generated by Django 3.0.2 on 2020-11-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20201112_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(blank=True, choices=[('e', 'Easy'), ('n', 'Normal'), ('h', 'Hard')], default='e', max_length=1, null=True),
        ),
    ]
