# Generated by Django 3.1.4 on 2021-01-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20210105_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('1', 'Single Player'), ('2', 'Two Player'), ('3', 'Three Player')], max_length=1),
        ),
    ]
