# Generated by Django 2.2.4 on 2020-11-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20201122_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('e', 'Easy'), ('n', 'Normal'), ('h', 'Hard')], default='e', max_length=10),
        ),
    ]
