# Generated by Django 2.2.4 on 2020-12-07 18:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20201122_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAdvertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('event', models.CharField(choices=[('e', 'Event'), ('a', 'Announcement'), ('o', 'Other')], max_length=1)),
                ('content', ckeditor.fields.RichTextField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EventAdvertisement',
                'verbose_name_plural': 'EventsAdvertisements',
                'managed': True,
            },
        ),
    ]
