# Generated by Django 2.2.4 on 2020-12-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_eventadvertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventadvertisement',
            name='active',
            field=models.BooleanField(default=True, help_text='ACTIVE : field is used to hide or show this post, if you will check this post it will be displayed in news feed else it will be hidden.'),
        ),
    ]
