# Generated by Django 2.2.4 on 2020-12-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20201208_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('des', 'Designing'), ('des', 'Development'), ('des', 'Testing')], max_length=1)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Application Update',
                'verbose_name_plural': 'Application Updates',
                'managed': True,
            },
        ),
    ]
