# Generated by Django 3.1.4 on 2020-12-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_appupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='players',
            field=models.CharField(choices=[('2', 'Two Players'), ('3', 'Three Players')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='appupdate',
            name='status',
            field=models.CharField(choices=[('des', 'Designing'), ('dev', 'Development'), ('des', 'Testing')], max_length=3),
        ),
    ]
