# Generated by Django 3.1.4 on 2020-12-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20201216_1940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventAdvertisement',
            new_name='Article',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'managed': True, 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
