# Generated by Django 3.1.4 on 2020-12-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20201217_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, to='application.Subject'),
        ),
    ]
