# Generated by Django 3.1.4 on 2020-12-20 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_quizcompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='teams',
        ),
    ]
