# Generated by Django 3.1.4 on 2020-12-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_remove_quiz_teams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
