# Generated by Django 3.1.4 on 2020-12-26 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_learningresourceattempts_learningresourceresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresourceattempts',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.quiz'),
            preserve_default=False,
        ),
    ]
