# Generated by Django 3.1.4 on 2020-12-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_learningresourceattempts_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresourceresult',
            name='attempts',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
