# Generated by Django 3.1.4 on 2020-12-29 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_auto_20201228_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='quiz',
            field=models.ForeignKey(default=26, on_delete=django.db.models.deletion.CASCADE, to='application.quiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, help_text='you can add details about yourself like your hobbies, favorite lines, code of life, bio or other details as well', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='include your phone number with your country code.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(default='images/profiles/male-avatar.jpg', height_field='image_height', help_text='Profile picture must be less then 500px of width and height, image must be in jpg, jpeg or png.', upload_to='images/profiles/', verbose_name='Profile Picture', width_field='image_width'),
        ),
    ]
