# Generated by Django 3.2.9 on 2021-11-18 05:43

from django.db import migrations, models
import src.application.models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='age_limit',
            field=models.PositiveIntegerField(help_text='Age must be greater then 5 and less than 18', validators=[src.application.models.is_more_than_eighteen]),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='players',
            field=models.CharField(choices=[('1', 'Single Player'), ('2', 'Two Players'), ('3', 'Three Players')], default='1', help_text='Select no of players for this quiz', max_length=1),
        ),
    ]
