# Generated by Django 3.1.6 on 2021-04-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20210413_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(through='src.application.QuizQuestion', to='src.application.Question'),
        ),
    ]
