# Generated by Django 3.1.6 on 2021-06-21 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20210520_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageVisibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='size of image less then 500*500 and format must be png, jpg or jpeg image file - ', null=True, upload_to='application/quizes/images/projects/')),
                ('screen_1', models.BooleanField(default=True)),
                ('screen_2', models.BooleanField(default=False)),
                ('screen_3', models.BooleanField(default=False)),
                ('quiz_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.quizquestion')),
            ],
            options={
                'verbose_name': 'Image Visibility',
                'verbose_name_plural': 'Images Visibility',
            },
        ),
        migrations.CreateModel(
            name='AudioVisibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('audio', models.FileField(blank=True, help_text='size of audio less then 5MB and format must be mps, ogg etc', null=True, upload_to='application/quizes/audios/projects/')),
                ('screen_1', models.BooleanField(default=True)),
                ('screen_2', models.BooleanField(default=False)),
                ('screen_3', models.BooleanField(default=False)),
                ('quiz_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.quizquestion')),
            ],
            options={
                'verbose_name': 'Audio Visibility',
                'verbose_name_plural': 'Audios Visibility',
            },
        ),
    ]
