# Generated by Django 3.2.9 on 2021-11-22 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20211121_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.subject')),
            ],
            options={
                'verbose_name_plural': 'Topics',
                'ordering': ['subject', '-created_on'],
            },
        ),
    ]
