# Generated by Django 3.2.9 on 2021-11-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(to='application.Topic'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='topics',
            field=models.ManyToManyField(to='application.Topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
