# Generated by Django 3.2.9 on 2021-12-13 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_quizmisc'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmisc',
            name='choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.questionchoice'),
            preserve_default=False,
        ),
    ]
