# Generated by Django 3.2.9 on 2021-12-26 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0009_quizmisc_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('class_name', models.CharField(blank=True, max_length=255, null=True)),
                ('class_section', models.CharField(blank=True, max_length=255, null=True)),
                ('school_email', models.CharField(blank=True, max_length=255, null=True)),
                ('school_address', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Students Profiles',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='total_correct_learning',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='total_correct_quizzes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='total_learning',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='total_quizzes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='screen',
            name='name',
            field=models.CharField(blank=True, help_text="Make sure to use the name as 'Screen 1' - 'Screen 2' and 'Screen 3'", max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
