# Generated by Django 3.2.9 on 2021-12-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20211229_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Not Provided', max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Student Grades',
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='total_correct_learning',
            new_name='total_times_correct_in_learning',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='total_correct_quizzes',
            new_name='total_times_correct_in_quizzes',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='total_learning',
            new_name='total_times_used_in_learning',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='total_quizzes',
            new_name='total_times_used_in_quizzes',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='total_players',
            new_name='total_attempted_students',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='total_teams',
            new_name='total_enrolled_students',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='total_teams_passed',
            new_name='total_enrolled_teams',
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_passed_student',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Guardian',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
