# Generated by Django 3.2.9 on 2022-01-01 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20211231_1700'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
