# Generated by Django 3.2.9 on 2022-01-01 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_delete_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.studentgrade'),
        ),
    ]
