# Generated by Django 3.2.9 on 2022-01-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_quiz_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
