# Generated by Django 3.2.9 on 2022-01-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_alter_studentgrade_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
