# Generated by Django 3.2.9 on 2022-01-04 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_alter_studentgrade_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.studentgrade'),
        ),
    ]
