# Generated by Django 3.2.9 on 2022-01-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_quiz_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='visible_on_home',
            field=models.BooleanField(default=False, help_text='Whether this quiz will be visible on website or not'),
        ),
    ]
