# Generated by Django 3.2.9 on 2022-01-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_quiz_visible_on_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(default='Description not provided yet.'),
        ),
    ]
