# Generated by Django 3.2.9 on 2022-01-30 16:43

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_auto_20220122_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', help_text='size of logo must be 500*500 and format must be png image file', keep_meta=True, null=True, quality=75, size=[400, 300], upload_to='images/profiles/'),
        ),
    ]
