# Generated by Django 3.2.9 on 2021-12-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211226_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='team_quizzes',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='zoom_user_id',
            field=models.CharField(default='ID not provided', max_length=255),
        ),
    ]
