# Generated by Django 3.2.9 on 2021-12-31 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20211231_1700'),
        ('accounts', '0008_auto_20211231_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.studentgrade'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='zoom_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
